// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfrmnionjbqgmgjydyry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmcm1uaW9uamJxZ21nanlkeXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTkxMzMsImV4cCI6MjA2NDc5NTEzM30.6FliQb0eSHwbCfiI9AwCdsTGo93-joQcVGVKp8slQmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);